apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      
      template:
        spec:
          containers:
          - name: busyboxcronjob
            image: busyboxplus:curl
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 200Mi
            livenessProbe:
              exec:
                command:
                 - /bin/sh
                 - -c
                 - curl http://localhost:8080/api/health
              initialDelaySeconds: 5
              periodSeconds: 5
          restartPolicy: OnFailure
