apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox
  namespace: mateapp
  labels:
    k8s-app: busybox
spec:
  selector:
    matchLabels:
      name: busybox
  template:
    metadata:
      labels:
        name: busybox
    spec:
      containers:
      - name: busybox
        image: busyboxplus:curl
        command: ["sh", "-c", "curl http://localhost:8080/api/health"]
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          hostPort: 30001